---
title: "p8105_hw6_jys2136"
author: "Jocelyn Sun"
date: "12/3/2021"
output: github_document
---

```{r setup, include = FALSE}

library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw()) + theme(axis.text.x = element_text(size = 9),
                              axis.text.y = element_text(size = 9),
                              legend.position = "bottom")

```


### Problem 1

```{r loading_data}

bwt_df = 
  read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>%
   mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    mrace = as.factor(mrace),
    malform = as.factor(malform)
  )

#checking for missing data
sapply(bwt_df, function(x) sum(is.na(x)))

```

There are no missing values in this data set as seen in the output.

#### Building a model

```{r}



```

